Pen 1736 svg updates
WPMedia/engine-theme-sdk pull request #214
Opened 2021-02-15 14:35 UTC by matthewroach

## Description

Update icon components to provide a context prop, to allow for the consumer to decide what context the icon will be used in. Thus allowing the SVG to have the correct attributes for accessibility.

## Jira Ticket
- [PEN-1736](https://arcpublishing.atlassian.net/browse/PEN-1736)

## Test Steps

- Verify icon components still render as before
- Verify icon components default to presentational and include the correct attributes
- Verify if an icon is used in the `image` context the correct attributes are applied

## Dependencies or Side Effects
_Examples of dependencies or side effects are:_
- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Update to css framework or SDK
- Dependency on another PR that needs to be merged first

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ ] Confirmed all the test steps above are working
- [ ] Confirmed there are no linter errors
- [ ] Confirmed this PR has reasonable code coverage
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

2021-02-18 19:49 UTC, vinnie-olsen requested changes

2021-02-18 19:49 UTC, vinnie-olsen commented on src/components/icons/ArrowRightIcon.tsx
> +  width = 24, height = 24, fill = '#000', title = 'Arrow Left', description = '', context = 'presentational',
`title` should be `Arrow Right` here

2021-02-18 19:49 UTC, vinnie-olsen commented on src/components/icons/ArrowUpIcon.tsx
> +  width = 24, height = 24, fill = '#000', title = 'Arrow Left', description = '', context = 'presentational',
`title` should be `Arrow Up` here

2021-02-18 19:49 UTC, vinnie-olsen commented on src/components/icons/EllipsisHorizontalIcon.tsx
> +  width = 24, height = 24, fill = '#000', title = 'EllipsisHorizontal', description = '', context = 'presentational',
Should this be changed to a `title` of `Ellipsis Horizontal` to be consistent in format with the `Ellipsis Vertical` title below?

2021-02-18 19:59 UTC, vinnie-olsen commented
@matthewroach one other thing I just thought of. On https://arcpublishing.atlassian.net/browse/PEN-676 , Brent had mentioned removing the `<desc>` tag for non-image SVG's and we discussed deferring that until a later ticket. Was this the ticket that was intended to remove those tags? I am still seeing those `<desc>` tags render on non-image SVG's but other than that, everything else looks good!

2021-02-19 10:36 UTC, matthewroach commented
@vinnie-olsen The `<desc>` children is a valid SVG item, that does have a use. For non-image SVG's the title and desc elements will now be ignored due to the use of `aria-hidden` - I've updated the code to not render those elements in non-image context, this helps with performance and redundant code

2021-02-19 15:25 UTC, JackHowa commented on .eslintrc.js
> +    'react/jsx-props-no-spreading': 'off',
thanks

2021-02-19 15:30 UTC, JackHowa approved these changes
storybook looks good, thanks

2021-02-19 15:31 UTC, merged