Uncompressing filter params
WPMedia/engine-theme-sdk pull request #97
Opened 2020-09-28 20:50 UTC by visionbegin

See PR template for this PR:

2020-09-29 17:16 UTC, JackHowa commented
is this a draft pr or ready for review? @visionbegin

2020-10-01 15:48 UTC, JackHowa requested changes
can you add a test case to this? I don't see any tests changed. For example, I'd expect https://github.com/WPMedia/engine-theme-sdk/blob/stable/src/components/Image/thumbor-image-url.test.ts#L3 to have a new test case with cm=t

2020-10-01 15:56 UTC, JackHowa commented
Also, can you update either documentation in the readme or in storybook? I noticed an in-line comment. but a customer or custom block developer won't see that unless they plumb the source code

2020-10-01 15:57 UTC, JackHowa commented on src/components/Image/thumbor-image-url.ts
> +   * In blocks/resizer-image-block/index.js (in fusion-news-theme-blocks),
good job adding developer documentation here

2020-10-01 16:46 UTC, visionbegin commented
@JackHowa Unit test added per you request

2020-10-01 19:23 UTC, JackHowa approved these changes
Cool thanks. did you add this fix documentation any where publicly like storybook or readme or image resizer docs (i sent you before)? Some devs will be psyched by this for perf reasons 
https://github.com/WPMedia/engine-theme-sdk/pull/97#issuecomment-702232188

2020-10-01 19:23 UTC, JackHowa commented on src/components/Image/thumbor-image-url.test.ts
> +    expect(buildThumborURL(targetImageKeyCompressed, '100x100', imageSource, resizerURL)).toBe('www.hey.resizer.com/r4YXPy4Eh2thx80bDTxRZM9Syhw=/100x100/filters:format(jpg):quality(70)/www.hey.com/ff
sweet

2020-10-01 20:00 UTC, merged